import Head from "next/head";
import Form from "../components/Body/Form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </>
  );
}
